# This is only used for standalone_migrations. In other contexts
# Travis.config.database will be used.

defaults: &defaults
  adapter: mysql2
  username: root
  host: localhost

test:
  <<: *defaults
  database: magnum_test

